### ISSUE TITLE
is there actually an rJava dependency?

### ISSUE THREAD

**Issue by e-kotov** [gesiscss/WhatsR#28]
@JuKo007 , hello! Is there actually an [`rJava`](https://github.com/s-u/rJava) dependency in the code? I can see it is mentioned in the readme, but I cannot find any traces in the codebase.

It's just that I am working on an R package [`rJavaEnv`](https://github.com/e-kotov/rJavaEnv) that focuses on helping ordinary users install Java into their project directory so that any `Java`/`rJava`-dependent package works properly without the struggles of installing Java manually. So I am actively looking for R packages that depend on `Java` (by invoking jars from command line) or `rJava`, and that could benefit from having `rJavaEnv` as a companion to help users to get started with minimal issues.

Are you perhaps planning to add new functions to `WhatsR` that will depend on `Java`/`rJava`? Please let me know.

Best,
Egor

**Comment by JuKo007** [comment]
Hi @e-kotov, there used to be an rJava dependency because WhatsR was using the ggmap package to plot locations. In the newest version on github, the location plotting is now done with leaflet instead. However, the CRAN version still uses the ggmap version that depends on rJava, thats why I didn't update the readme yet. With the next CRAN release, there should be no rJava dependency and/or mention anymore.

**Comment by e-kotov** [comment]
Got it! Thanks!
